# Generated by Django 3.1.2 on 2020-10-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Item is in stock'), ('Out Of Stock', 'Item is out of stock'), ('Not Available', 'Item is not in inventory')], max_length=15),
        ),
    ]
